[Software_engineering]
name = "Hello-world"
version = "1.0.0"
description = "This a python package example project."
requires-python = ">=3.8"
authors = [
    {name = "John Doe", email = "john@example.com"}
]
dependencies = [
    "numpy",
    "pandas",
]
